### PR TITLE
recipe: attempt to update to conda build 3

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
@conda-forge-admin, please rerender

**Comment by MatthieuDartiailh** [comment]
@conda-forge-admin, please rerender

**Comment by MatthieuDartiailh** [comment]
@blink1073 could you review this ? I am not really sure I got the conda build 3 settings right.

**Comment by blink1073** [comment]
LGTM!

**Comment by MatthieuDartiailh** [comment]
Thanks @blink1073.

Merging

**Pull request merged**
