### PR TITLE
update recipe for atom 0.4.1

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
I have no idea what is the meaning of the failures on appveyor. Any idea @blink1073 ?

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender.

**Comment by blink1073** [comment]
@MatthieuDartiailh, when in doubt, try the above ^^  :smile:.

**Comment by MatthieuDartiailh** [comment]
Oh thanks @blink1073 I really should remember this trick !
Merging !

**Pull request merged**
